"""empty message

Revision ID: 29f4c164e640
Revises: e3246a8640a5
Create Date: 2022-08-16 02:52:29.961630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f4c164e640'
down_revision = 'e3246a8640a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.drop_constraint('shows_venu_id_fkey', 'shows', type_='foreignkey')
    op.create_foreign_key(None, 'shows', 'venues', ['venue_id'], ['id'])
    op.drop_column('shows', 'venu_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venu_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shows', type_='foreignkey')
    op.create_foreign_key('shows_venu_id_fkey', 'shows', 'venues', ['venu_id'], ['id'])
    op.drop_column('shows', 'venue_id')
    # ### end Alembic commands ###
